### ISSUE TITLE
Trouble installing in Coda 2.0.9

### ISSUE THREAD

**Issue by bartderijk** [emmetio/Emmet.codaplugin#15]
I went trough the installation steps as instructed in the readme file but after I click on Emmet.codaplugin the plugin just won't install. It doesn't show up in the plugins menu tab while other plugins do. Any suggestions?

**Comment by dremmers** [comment]
I am having the same issue, I download the zip to my desktop, unzipped/unpacked it, and then renamed the folder to Emmet.codaplugin. Once I double click to install it it brings up my coda plug-in screen but it doesn't show up or install at all. Any ideas?

**Comment by dremmers** [comment]
I am on version Coda V 2.5.7
