### ISSUE TITLE
Incompatible with Coda 2.5.4 and Yosemite 10.10.3.

### ISSUE THREAD

**Issue by Arcrammer** [emmetio/Emmet.codaplugin#25]

**Comment by amityweb** [comment]
Yeah, I installed this and nothing happens

**Comment by Arcrammer** [comment]
It's a darned shame because this is a remarkable plug-in, but I don't want to use Sublime Text for it...

**Comment by jeff-swearingen** [comment]
Hey guys,

If you haven't seen it already, this thread may have the answer you're looking for:

https://github.com/emmetio/Emmet.codaplugin/issues/18#issuecomment-64986379

Hope it helps.

**Comment by sergeche** [comment]
Just released new Emmet version for Coda: http://emmet.io/download/coda/
Duplicate of #23
