### ISSUE TITLE
New Emmet for Coda Support

### ISSUE THREAD

**Issue by toshi-t** [emmetio/Emmet.codaplugin#28]
In first, I'm afraid my expressions may be rude or hard to read, because I'm not so good at English. But please, please be patient.

Would not available the shortcut in free version?
If available How do I use it?

![menu](https://cloud.githubusercontent.com/assets/5819343/15844424/3ca69d16-2ca5-11e6-903c-b9f11a6de5dd.png)

I was watched File "KeyboardShortcuts.plist" .
But I have no idea method to fix.
![shortcut](https://cloud.githubusercontent.com/assets/5819343/15844427/42f02886-2ca5-11e6-925c-59db977d1250.png)

**Comment by toshi-t** [comment]
Sorry. Was self resolved.

**Comment by sergeche** [comment]
This is not right, you should see shortcuts near each available action. How did you managed to solve this issue?

**Comment by toshi-t** [comment]
I read this link.
[https://github.com/emmetio/Emmet.codaplugin#readme](url)

I have tried the method that is writen there.

>  Go to OSX’ System Preferences > Keyboard > Keyboard Shortcuts > Application Shortcuts.
>     Click on “plus” sign to add a new application shortcut.
>     Pick “Coda” app, enter menu item name with the action you want to change and type a new keyboard shortcut.

Did you mean Is this method wrong?

**Comment by sergeche** [comment]
It’s the right way to change shortcut, but you should see default shortcuts when you start Coda with Emmet. According to your screenshot, there is no default shourtcuts

**Comment by toshi-t** [comment]
Yes, default shortcuts were none.

I had repeated many times install and unistall.
But, shortcuts were not changed.

Coda ver 2.5.16
OS X El capitan ver 10.11.5

**Comment by sergeche** [comment]
Published version 1.0.2, it contains fixes that enable default action shortcuts

**Comment by toshi-t** [comment]
Oh! Thank you so much!
